/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yu Hann
 */
import java.io.File;
import java.io.FileWriter;
import java.time.LocalDate;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Add_Car extends javax.swing.JFrame {

    /**
     * Creates new form Add_Car
     */
    public Add_Car() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CarPlateNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CarBrand = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CarColour = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CarPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        jLabel1.setText("Add a New Car!");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Enter Car Plate Number");

        CarPlateNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarPlateNumberActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Enter Car Brand");

        CarBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarBrandActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Enter Car Colour");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Enter Car Price");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Click here to add car");

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setText("Proceed");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CarPrice)
                            .addComponent(CarPlateNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarBrand)
                            .addComponent(CarColour, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(334, 334, 334)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 368, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(345, 345, 345))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarPlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarPlateNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarPlateNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarPlateNumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String carPlateNumber = CarPlateNumber.getText();
        String carBrand = CarBrand.getText();
        String carColour = CarColour.getText();
        String carPrice = CarPrice.getText();
        LocalDate currentDate = java.time.LocalDate.now();
        try
        {
            FileWriter Writer = new FileWriter ("carList.txt", true);
            int firstCarID = 1;
            int count = 0;
            try
            {
                File file = new File("carList.txt");
                Scanner sc = new Scanner(file);
                while(sc.hasNextLine()){
                    sc.nextLine();
                    count++;
                
                }
            }
            catch (Exception e){
                e.getStackTrace();
            }
            if (count == 0){
                if (count < 10){
                    Writer.write("CAR000"+String.format("%s", firstCarID)+";"+carPlateNumber+";"+carBrand+";"+carColour+";"+carPrice+";"+String.format("%s", currentDate)+";"+"Y");
                    Writer.write(System.getProperty("line.separator"));
                    Writer.close();
                    JOptionPane.showMessageDialog(null,"New car has successfully being added.\n Car ID would be CAR000"+firstCarID);
                    setVisible(false);
                    new AdminMenu().setVisible(true);
                }
                if (count >= 10 & count < 100){
                    Writer.write("CAR00"+String.format("%s", firstCarID)+";"+carPlateNumber+";"+carBrand+";"+carColour+";"+carPrice+";"+String.format("%s", currentDate)+";"+"Y");
                    Writer.write(System.getProperty("line.separator"));
                    Writer.close();
                    JOptionPane.showMessageDialog(null,"New car has successfully being added.\n Car ID would be CAR00"+firstCarID);
                    setVisible(false);
                    new AdminMenu().setVisible(true);
                }
                if (count >= 100 & count < 1000){
                    Writer.write("CAR0"+String.format("%s", firstCarID)+";"+carPlateNumber+";"+carBrand+";"+carColour+";"+carPrice+";"+String.format("%s", currentDate)+";"+"Y");
                    Writer.write(System.getProperty("line.separator"));
                    Writer.close();
                    JOptionPane.showMessageDialog(null,"New car has successfully being added.\n Car ID would be CAR0"+firstCarID);
                    setVisible(false);
                    new AdminMenu().setVisible(true);
                }
                if (count >= 1000){
                    Writer.write("CAR"+String.format("%s", firstCarID)+";"+carPlateNumber+";"+carBrand+";"+carColour+";"+carPrice+";"+String.format("%s", currentDate)+";"+"Y");
                    Writer.write(System.getProperty("line.separator"));
                    Writer.close();
                    JOptionPane.showMessageDialog(null,"New car has successfully being added.\n Car ID would be CAR"+firstCarID);
                    setVisible(false);
                    new AdminMenu().setVisible(true);
                }
                
            }else{
                int carID=firstCarID+count;
                if (count < 10){
                    Writer.write("CAR000"+String.format("%s", carID)+";"+carPlateNumber+";"+carBrand+";"+carColour+";"+carPrice+";"+String.format("%s", currentDate)+";"+"Y");
                    Writer.write(System.getProperty("line.separator"));
                    Writer.close();
                    JOptionPane.showMessageDialog(null,"New car has successfully being added.\n Car ID would be CAR000"+carID);
                    setVisible(false);
                    new AdminMenu().setVisible(true);
                }
                if (count >= 10){
                    Writer.write("CAR00"+String.format("%s", carID)+";"+carPlateNumber+";"+carBrand+";"+carColour+";"+carPrice+";"+String.format("%s", currentDate)+";"+"Y");
                    Writer.write(System.getProperty("line.separator"));
                    Writer.close();
                    JOptionPane.showMessageDialog(null,"New car has successfully being added.\n Car ID would be CAR00"+carID);
                    setVisible(false);
                    new AdminMenu().setVisible(true);
                }
                if (count >= 100){
                    Writer.write("CAR0"+String.format("%s", carID)+";"+carPlateNumber+";"+carBrand+";"+carColour+";"+carPrice+";"+String.format("%s", currentDate)+";"+"Y");
                    Writer.write(System.getProperty("line.separator"));
                    Writer.close();
                    JOptionPane.showMessageDialog(null,"New car has successfully being added.\n Car ID would be CAR0"+carID);
                    setVisible(false);
                    new AdminMenu().setVisible(true);
                }
                if (count >= 1000){
                    Writer.write("CAR"+String.format("%s", carID)+";"+carPlateNumber+";"+carBrand+";"+carColour+";"+carPrice+";"+String.format("%s", currentDate)+";"+"Y");
                    Writer.write(System.getProperty("line.separator"));
                    Writer.close();
                    JOptionPane.showMessageDialog(null,"New car has successfully being added.\n Car ID would be CAR"+carID);
                    setVisible(false);
                    new AdminMenu().setVisible(true);
                }
            }
        }
        catch(Exception E)
        {
            JOptionPane.showMessageDialog(null, "Error! Try Again!");
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CarBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarBrandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CarBrand;
    private javax.swing.JTextField CarColour;
    private javax.swing.JTextField CarPlateNumber;
    private javax.swing.JTextField CarPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
