import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author KhooWennHonn(TP065779)
 */
public class CustomerProfile extends javax.swing.JFrame {
    String cus_ID;
    ArrayList<Customer> cusList = new ArrayList<>(); //array list
    public CustomerProfile(String cusID) {
        cus_ID = cusID;
        initComponents();
        label_cusID.setText(cusID);
        // make the text fields uneditable
    }

    private CustomerProfile() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public String[] getRecord(){
        try{
        //Read from customerlist (whereever u place it)
        File customer = new File("customerList.txt");
        FileReader fr = new FileReader(customer);
        BufferedReader br = new BufferedReader(fr);
        String line = br.readLine();
        while (line != null){
            String [] split = line.split(";");
            String testID = split[0];
            if (testID.equals(cus_ID)){
                String name = split[1];
                String email = split[2];
                String contact = split[3];
                String ic = split[4];
                String password = split[5];
                String gender = split[6];
                String[] record = {name,email,contact,ic,password,gender};
                System.out.println(Arrays.toString(record));
                return record;
            }
            line = br.readLine();
        }
        fr.close();
        br.close();
        }catch (FileNotFoundException e) {
            System.out.println("File not found!");
        }catch (Exception ex){
            System.out.println("Other errors found!");
        }
        String[] record = {"Not Found"};
        return record;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        button_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_cusID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        combo_gender = new javax.swing.JComboBox<>();
        txt_ic = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        button_edit = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        button_show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel1.setText("Customer Profile");

        button_back.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        button_back.setText("Back");
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Email");

        label_cusID.setText("cusID");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Contact Number");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("IC Number");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Gender");

        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Undefined" }));

        button_edit.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        button_edit.setText("Edit!");
        button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editActionPerformed(evt);
            }
        });

        button_save.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        button_save.setText("Save!");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        button_show.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        button_show.setText("Show Profile");
        button_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(label_cusID, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(button_back)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_name)
                            .addComponent(txt_email)
                            .addComponent(txt_contact)
                            .addComponent(combo_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ic)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(button_show)
                .addGap(63, 63, 63)
                .addComponent(button_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(button_save)
                .addGap(0, 128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(button_back)
                    .addComponent(label_cusID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combo_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_edit)
                    .addComponent(button_save)
                    .addComponent(button_show))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        new CustomerUI(cus_ID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_backActionPerformed

    private void button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editActionPerformed
        //txt_name.setEditable(true);
        txt_email.setEditable(true);
        txt_contact.setEditable(true);
        //txt_ic.setEditable(true); should not be editable
        txt_password.setEditable(true);
        //combo_gender.setEnabled(true); should not be editable
    }//GEN-LAST:event_button_editActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        File customer = new File("customerList.txt");
        try{
            BufferedReader br = new BufferedReader(new FileReader(customer));
            String line = br.readLine();
            while (line != null)
            {
                String [] split = line.split(";");
                if (split[0].equals(cus_ID)){
                    String cID = cus_ID;
                    String name = txt_name.getText();
                    String email = txt_email.getText();
                    String contact = txt_contact.getText();
                    String ic = txt_ic.getText();
                    String pass = txt_password.getText();
                    String gender = (String)combo_gender.getSelectedItem();
                    cusList.add(new Customer(cID,name,email,contact,ic,pass,gender));
                } else {
                    String cID = split[0];
                    String name = split[1];
                    String email = split[2];
                    String contact = split[3];
                    String ic = split[4];
                    String pass = split[5];
                    String gender = split[6];
                    cusList.add(new Customer(cID,name,email,contact,ic,pass,gender));
                }
                line = br.readLine();
            }
            br.close();
            FileWriter fw = new FileWriter(customer,false);
            for (int RecNo = 0; RecNo<cusList.size();RecNo++){
                Customer Temp;
                Temp = cusList.get(RecNo);
                String cID = Temp.getCus_ID();
                String name = Temp.getCus_Name();
                String email = Temp.getEmail();
                String contact = Temp.getContact_Num();
                String ic = Temp.getIC_Num();
                String pass = Temp.getPassword();
                String gender = Temp.getGender();
                String record = cID+";"+name+";"+email+";"+contact+";"+ic+";"+pass+";"+gender+"\n";
                fw.write(record);
            }
            fw.close();
        }catch (FileNotFoundException ex){
            System.out.println("File customerList.txt not found!");
        }catch (IOException io){
            System.out.println("IO Exception found!");
        }
        JOptionPane.showMessageDialog(this,"Profile Update Success!");
    }//GEN-LAST:event_button_saveActionPerformed

    private void button_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_showActionPerformed
        String[] rec = getRecord();
        txt_name.setText(rec[0]);
        txt_email.setText(rec[1]);
        txt_contact.setText(rec[2]);
        txt_ic.setText(rec[3]);
        txt_password.setText(rec[4]);
        combo_gender.setSelectedItem(rec[5]);
        txt_name.setEditable(false);
        txt_email.setEditable(false);
        txt_contact.setEditable(false);
        txt_ic.setEditable(false);
        txt_password.setEditable(false);
        combo_gender.setEnabled(false);
    }//GEN-LAST:event_button_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustomerProfile().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_back;
    private javax.swing.JButton button_edit;
    private javax.swing.JButton button_save;
    private javax.swing.JButton button_show;
    private javax.swing.JComboBox<String> combo_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label_cusID;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_ic;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
